Support comitting as different user

diff --git a/bin/gits b/bin/gits
--- a/bin/gits
+++ b/bin/gits
@@ -789,19 +789,8 @@ gits:status:fetch() {
 #
 ###/doc
 
-gits:check-commit() {
-    local x
-    for x in "$@"; do
-        if [[ "$x" =~ ^-mm?$ ]]; then
-            return 1
-        fi
-    done
-
-    return 0
-}
-
 gits:diff() {
-    gits:check-commit "$@" || {
+    gits:commit:check "$@" || {
         gits:commit "$@"
         return
     }
@@ -958,14 +947,16 @@ function askuser:choose {
     done
 }
 
-### Commit -m[m] [MESSAGE] Usage:help-commit
+### Commit: gits [FILES] -m[m][/PROFILE] [MESSAGE] Usage:help-commit
 #
-# After a series of items, if -m or -mm are found, performs an add + commit
+# After a series of files, if -m or -mm are found, performs an add + commit
 #
 # -m adds a new commit
 # -mm amends the last commit
 #
 # if no MESSAGE is suppplied, an editor session is started
+#
+# if `/PROFILE` is set, commits using user details from the relevant profile, then reverts the details
 #
 # If the current branch is master, and `allow_master_commits` in .gits-shorthands is not set,
 #   then prompt the user whether to allow.
@@ -973,6 +964,21 @@ function askuser:choose {
 #   When set to `false`, never prompts and prevents comitting to master
 #
 ###/doc
+
+GITS_commitflag="^-m(m|/([a-zA-Z_-]+))?$"
+
+gits:commit:check() {
+    local x
+    for x in "$@"; do
+        if [[ "$x" =~ $GITS_commitflag ]]; then
+            return 1
+        elif [[ "$x" =~ ^-mm/ ]]; then
+            out:fail "Cannot change profile when amending a commit. Reset and re-commit."
+        fi
+    done
+
+    return 0
+}
 
 gits:commit() {
     gits:local-help commit "$@"
@@ -985,14 +991,16 @@ gits:commit() {
     arguments=(:)
     item="$1"
 
-    while [[ ! "$item" =~ ^-mm?$ ]]; do
+    while [[ ! "$item" =~ $GITS_commitflag ]]; do
         files+=("$item")
         shift
         item="$1"
     done
     shift
 
-    if [[ "$item" = -mm ]]; then
+    GITS_profile_switch="${BASH_REMATCH[2]:-}"
+
+    if [[ "$item" =~ ^-mm ]]; then
         arguments+=(--amend)
     fi
 
@@ -1004,7 +1012,22 @@ gits:commit() {
         gits:run add "${files[@]:1}"
     fi
 
-    gits:run commit "${arguments[@]:1}"
+    if [[ -n "${GITS_profile_switch:-}" ]]; then
+        configname="$(git config user.name)"
+        configmail="$(git config user.email)"
+        gits:profiles:save temp "$configname" "$configmail"
+        gits:profiles:apply "$GITS_profile_switch"
+    fi
+
+    gits:run commit "${arguments[@]:1}" || :
+
+    if [[ -n "${GITS_profile_switch:-}" ]]; then
+        gits:commit:profile-restore
+    fi
+}
+
+gits:commit:profile-restore() {
+    gits:profiles:apply temp
 }
 
 gits:commit:check_master() {
